spring.application.name=api-gateway
spring.profiles.active=local

server.port=${SERVER_PORT}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

kafka.topics.user-commands=${KAFKA_TOPIC_USER_COMMANDS}
kafka.topics.group-commands=${KAFKA_TOPIC_GROUP_COMMANDS}
