spring.application.name=user-service
spring.profiles.active=local


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID}

kafka.topics.user-commands=${KAFKA_TOPIC_USER_COMMANDS}
kafka.topics.user-events=${KAFKA_TOPIC_USER_EVENTS}