spring.application.name=wishlist-service
spring.profiles.active=local
spring.main.web-application-type=none

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5435/wishlist_db}
spring.datasource.username=${DB_USERNAME:wishlist_admin}
spring.datasource.password=${DB_PASSWORD:wishlist_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:wishlist-service}

kafka.topics.group-events=${KAFKA_TOPIC_GROUP_EVENTS:group.events}
kafka.topics.wishlist-commands=${KAFKA_TOPIC_WISHLIST_COMMANDS:wishlist.commands}
kafka.topics.wishlist-events=${KAFKA_TOPIC_WISHLIST_EVENTS:wishlist.events}
